version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.50" # Redis agora é mais crítico
          memory: "200MB" # Um pouco mais de memória para os dados

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_load_balancer
    networks:
      - backend
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: rinha
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      HTTP_PORT: "9999"
      PAYMENT_WORKERS: "100"
      PAYMENT_URL_DEFAULT: "http://payment-processor-default:8080"
      PAYMENT_URL_FALLBACK: "http://payment-processor-fallback:8080"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "70M"

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: rinha
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      HTTP_PORT: "9999"
      PAYMENT_WORKERS: "100"
      PAYMENT_URL_DEFAULT: "http://payment-processor-default:8080"
      PAYMENT_URL_FALLBACK: "http://payment-processor-fallback:8080"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "70M"

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true